### ISSUE TITLE
1x option a possibility?

### ISSUE THREAD

**Issue by helmernate** [PeteJobi/RealEsrganUpscalerGUI#4]
Thanks for putting this together. Works like a charm. Any way you could add a 1x option to the upscaling choices so I could run the AI to 4K sources without upscaling?

**Comment by PeteJobi** [comment]
Hello @helmernate. That will not be possible, as the underlying models do not support 1x upscale. Can I ask why you want to run your content through the software without actually upscaling? That's all the software does.

**Comment by helmernate** [comment]
Thanks for your response. The 4K master mkv files I get from blu rays are,
a lot of the time, soft and grainy. Running them through the ai process at
1x upscale(same size as source) sharpens the picture and eliminates the
grain, giving me an improved looking 4k master. I've used dvdfab to do this
but it takes an extremely long time to render. Your program upscales about
6 times as fast as dvdfab on my computer. Your program is perfect for
everything else. And the ai model I'm using for dvdfab says real ESRGAN and
it allows me to do same as source size rendering. I think it's possible.
And if your program had that it would be perfect for my use. Thanks again
for putting it out there. I'm using it right now.

**Comment by PeteJobi** [comment]
Oh, sharpening. I see. 

This software is basically just a GUI that uses another underlying software ([realesrgan-ncnn-vulkan.exe](https://github.com/PeteJobi/RealEsrganUpscalerGUI/releases/download/v.4.0.0/realesrgan-ncnn-vulkan.exe)), which only offers upscale options of 2x, 3x and 4x. You can see that in the Readme for [their repo](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan). 1x might be possible on a lower level, but the software the GUI is based on doesn't support it. It won't be possible for this GUI.

Thanks for your kind words on the software.

**Comment by helmernate** [comment]
Any idea where I might be able to find some software similar to yours that
I could use to do what I'm talking about faster than dvdfab? Right now it
renders at around .24 frames per second. Scarface took me around 300 hours
of render time.

**Comment by PeteJobi** [comment]
None I know that does 1x upscale. Try focusing your search on enhancers instead of upscalers and you might find something.

Are you the one consuming the videos? If so, and if disk space is not an issue, upscaling to 2x, and then watching the video in the same window size as the original resolution, should have the same sharpening effect.

**Comment by helmernate** [comment]
Thanks for all your help. I will give that a whirl. Disk size is a bit of
an issue but I'll see what can be done. 8K is just down the pike. Take it
easy.

**Comment by PeteJobi** [comment]
You're welcome. I know you're serious about this with the mention of 4k master and 300 hours of processing so I hope you find something that makes things faster for you. I'll go ahead and close this issue.
